version: '3'
services:
  api:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
      - ./assets:/app/assets
      - ./media:/app/media
    depends_on:
      - postgres
      - redis
  celery:
    build: .
    command: celery -A luxe worker -l info
    env_file:
      - .env
    entrypoint: "celery.sh"
    volumes:
      - .:/app
    depends_on:
      - redis
      - api
  postgres:
    image: postgres:13
    restart: always
    env_file:
      - .env
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
  redis:
    image: redis:6
    env_file:
      - .env
    volumes:
      - ./.data/redis:/data
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    env_file:
      - .env
    volumes:
      - ./.conf/nginx:/etc/nginx/conf.d
    depends_on:
      - api
